### ISSUE TITLE
Backend build fails because of Awscrt

### ISSUE THREAD

**Issue by AdrienCesar** [aws-samples/greengrass-v2-local-web-server#4]
Good evening,
I have tried to build this for a while now and i figured i should just ask for help.
After following the installation steps it always falls apart when i use **gdk component build**.

error: legacy-install-failure
× Encountered error while trying to install package.
╰─> awscrt

the full logs are here https://pastebin.com/U4kTdXEy (the end is interesting)
My System is a Raspberry Pi 4 8gb
Debian "bullseye" amd64

Has anyone else experienced a similar issue?
If anyone has questions feel free to ask.
thanks

**Comment by saranyailla** [comment]
What version of `awscrt` is being installed here? You can update the code to install the [latest version](https://pypi.org/project/awscrt/) of it and check if it's working? If the issue still persists, you can reach out to [awscrt](https://github.com/awslabs/aws-crt-python) and raise the issue there as what you're seeing here is not related to Greengrass component or GDK.

**Comment by AdrienCesar** [comment]
The Dockerfile installs Awsiotsdk 1.7.1 which subsequently installs awscrt 0.17.1.
I have updated it to the latest version with no effect. (1.19.0 and 0.19.1)
The process fails while trying to build the wheel for awscrt.

**Comment by AdrienCesar** [comment]
Okay, it way a problem with the Architecture.
It simply doesnt work on 32-Bit.

**Comment by AdrienCesar** [comment]
Okay, it way a problem with the Architecture.
It simply doesnt work on 32-Bit.
