### ISSUE TITLE
tag "main" causes git warning refname main is ambiguous due to branch name "main"

### ISSUE THREAD

**Issue by beepscore** [aws-samples/greengrass-v2-local-web-server#5]
After cloning repo, a terminal command like "git checkout main" throws "warning: refname 'main' is ambiguous."
git is unsure if reference is to tag "main" or branch "main".
In my local copy, deleting tag "main" appears to fix the issue.
Please delete tag "main" if not needed.
Thanks!

**Comment by MikeDombo** [comment]
Thank you. 

Removed.
